global using Azure.Identity;
global using Dapper;
global using FluentValidation;
global using Google.Protobuf.Collections;
global using Grpc.Core;
global using MediatR;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Mvc;
global using Ordering.API;
global using Ordering.API.Application.Behaviors;
global using Ordering.API.Application.Commands;
global using Ordering.API.Application.IntegrationEvents;
global using Ordering.API.Application.IntegrationEvents.EventHandling;
global using Ordering.API.Application.IntegrationEvents.Events;
global using Ordering.API.Application.Models;
global using Ordering.API.Application.Queries;
global using Ordering.API.Application.Validations;
global using Ordering.API.Extensions;
global using Ordering.API.Infrastructure;
global using Ordering.API.Infrastructure.Services;
global using Microsoft.Extensions.Options;
global using Polly;
global using Polly.Retry;
global using System.Data.Common;
global using System.Runtime.Serialization;

global using AppCommand = Ordering.API.Application.Commands;
global using ApiModels = Ordering.API.Application.Models;